# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba893f44ddc004748c954064d97c192935cb24bfb0cafb0ff7a3b77fd8f8dd58b13c37dad34709338e8a2e85fc8e987dcae10be5712cbbd8948b1650003dd87

test:
  secret_key_base: 2017b04f49cdc76329e8ea94656b9f5944a8780e3179ac11a9a31027c420be5bcd57c6ce0422de26aa61d5d1558d76e287bbd3b98258eb0d9b2176632c91ce02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
